name: test_vars
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: dbx_dabs_tst

jobs:
  show-vars:
    name: job-vars
    runs-on: ubuntu-latest
    environment: dbx_dabs_tst
    steps:
    - name: show-vars
      run: |
        echo "my org secret : $TESTSECRET"
        echo "my org var: $orgvar"
      env: 
        TESTSECRET: ${{ secrets.DATABRICKS_TOKEN }}
        orgvar: ${{ vars.TEST_ENV_VAR }}
